version: '3'
services:
    mysql: 
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: demo
            MYSQL_DATABASE: web
        ports: 
            - "3306:3306"
            
    course-service: 
        image: course-service
        ports: 
            - "8081:8080"
        depends_on:
            - mysql
        environment:
            SPRING_APPLICATION_NAME: courseMS
            SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web?characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: demo